### ISSUE TITLE
My lock screen notification turned into a floating icon! 

### ISSUE THREAD

**Issue by Dalarialus** [medicalid/issues#208]
No obvious way to turn it back. Is this a bug?

**Comment by laurentpellegrino** [comment]
Thanks for reaching out.

This is not a bug. Recent versions of the app have replaced the notification and overlay mode by a floating icon. The change was made because previous solutions were unstable and relying on features that are not recommended by Google. As a consequence, I risked an app suspension :(

The floating icon solution is the new way to go. However, I am working on new layouts (floating banner and floating overlay) that will be similar to the old solutions that were existing.

I cannot say exactly when new layouts will be available but it should be between the end of February and end of March.
