### ISSUE TITLE
New phone

### ISSUE THREAD

**Issue by pamsbeans** [medicalid/issues#236]
I just got a new phone. How do I transfer my medical id information? Do I have to re-enter it all?

**Comment by laurentpellegrino** [comment]
Sorry for not replying before. Here is an answer in the case it can help others in the future: 

To move data, one solution is to create a backup file on the old device, move it to the new device, and import that file from the Medical ID app. Note that this is possible with the premium version of the app only (the free version does not support this).

Here is a step by step guide:

1) Take your old device, open the Medical ID app, and create a backup as shown in this video:
https://youtu.be/taH9QbVc_Ik

2) Now that you have the backup file created, you need to move it to your new device so that you can import it into the Medical ID app.  When you created the backup file, a new entry appeared. This entry includes among others 2 big buttons named "Restore" and "Delete". Next to the delete one, there is a Cloud icon tap on it to select an app to transfer the backup file. Here you can use different methods (email, Google Drive, etc.). For the sake of the explanation, use Google Drive as shown in this video:
https://www.youtube.com/watch?v=AVcWO72snDA&feature=youtu.be

3) Once done, take your new device. The last step is to import your backup file from Google Drive. Go to the backup screen of the Medical ID app, click on the + button at the bottom right side and select Import as shown in this video:
https://www.youtube.com/watch?v=tlUWjgOu78U&feature=youtu.be

On the screen that appears, use your Google Drive account (you should be connected with the same email as you used when you pushed the backup file from your old device), and select the backup file. Once selected it should import into the Medical ID app and you should see a new entry appear. Tap on the "Restore" button and your data is back.

Instead of using Google drive, you can also transfer the backup file by email. You will then have to save it on your device's local storage before importing the file back from Medical ID.
