### ISSUE TITLE
BankID 

### ISSUE THREAD

**Issue by appeltrees** [medicalid/issues#244]
When I want to use BankID, my bank forces me to shut down accessibility services (Medical ID).

**Comment by laurentpellegrino** [comment]
Here is a video that shows the steps to enable the Medical ID accessibility service. If you want to disable it, simply toggle the switch button to 'off' instead of 'on':

https://www.youtube.com/shorts/Vj-P45M-Aqk

I'm not sure about BankID, but if it prevents the use of accessibility services, you should check with them. The issue lies with the app that restricts others. They might claim it's for security reasons, but preventing the use of accessibility services is quite problematic...

**Comment by appeltrees** [comment]
Thank you for your answer. I know how to use Medical ID, but, it is my bank
who prevents me from using Medical ID, claiming it is for my security. I
have phoned and mailed them a lot of times and now they have answered me
that they will look into it. So far nothing has happened.
What remains now for me, is to change bank.

Regards

Den mån 13 maj 2024 kl 12:58 skrev Laurent Pellegrino <
***@***.***>:

**Comment by laurentpellegrino** [comment]
Unfortunately, there is nothing I can do at my level. Sorry for not being more helpful.

**Comment by appeltrees** [comment]
Thank you for answering 🤗. It is not easy for anyone to be helpful in this qustion. Only BankID can fix their stupid techniques. I mostly wondered if more people has hade the same experion and if they have recevied any support from BankID. There is just wait and see, and change bank.
Greetings from appletree 🙂.

Skickat från Proton Mail-mobil

-------- Originalmeddelande --------
Den 15 maj 2024 23:42, Laurent Pellegrino skrev:
